### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by Tobias-Fischer** [neuromorphicsystems/event_stream#1]
Hi, I'd like to package this on conda-forge. Unfortunately, the license file is missing, which is needed for that. I'd be great if you could add one.

Many thanks,
Tobi

**Comment by Tobias-Fischer** [comment]
Ping @aMarcireau

**Comment by aMarcireau** [comment]
Hi @Tobias-Fischer. I just added a license. Sorry for the slow reply.
